#!/bin/bash
usage()
{
cat << EOF
usage: $0 [OPTIONS] [--] COMMAND

Takes the output of a command and reports it to sensu.

OPTIONS:
   -h      Show help
   -n      Specify the name of the check. Defaults to the name of the command you run.
   -l      Send the output of the command to logger as well as Sensu.
   -n      Dry run, send the output what would be sent to Sensu to stderr.
   -h      String of an array of handlers. Defaults to empty. (use default handlers)
   -c      Specify custom json to cover a need that I can't think of. (see examples)
   -v      Verbose mode.

Examples:

    $0 /bin/false
    (reports the output to sensu sliently, with a name of /bin/false)

    $0 -l -n "Daily Apt Get Cron" /usr/bin/apt-get update
    (Get a sensu alert when your daily apt-get cron job fails, and get logs to syslog)

    $0 -h "['email', 'pagerduty']" -- /usr/bin/my_critical_command
    (Be explicity about handlers to use. Optional -- to separate the command)

    $0 -n "Special Check" -c '"playbook": "http://wiki/special_check", "metric: false"' -- /usr/bin/special_check
    (For when you need extra json in the output)
    
EOF
}

#echo '{"name": "some-check-name", "output": "I failed unfortunately", "status": 2}' > /dev/tcp/localhost/3030

